
/* CLAUSES */

CREATE TABLE TCS_EMPLOYEES (EMPID INT,EMP_LOCATION VARCHAR(20),
EMPNAME VARCHAR(20),EMP_POSITION VARCHAR(20),
EMPSALARY MONEY)

SELECT *FROM TCS_EMPLOYEES

INSERT INTO TCS_EMPLOYEES VALUES (1,'PUNE','JOHN','MANAGER',1200)
INSERT INTO TCS_EMPLOYEES VALUES (2,'BIHAR','PETER','TEAM LEADER',1000)
INSERT INTO TCS_EMPLOYEES VALUES (3,'NOIDA','HARRY','MODULE LEAD',1100)
INSERT INTO TCS_EMPLOYEES VALUES (4,'DELHI','MICHEAL','MANAGER',1500)
INSERT INTO TCS_EMPLOYEES VALUES (5,'BANGALORE','JOHNSON','TEAM LEADER',1150)
INSERT INTO TCS_EMPLOYEES VALUES (6,'ANDRA','JAMES','MODULE LEAD',1300)
INSERT INTO TCS_EMPLOYEES VALUES (7,'HYDERABAD','SURYA','MANAGER',2000)
INSERT INTO TCS_EMPLOYEES VALUES (8,'TAMIL NADU','VIJAY','TEAM LEADER',1800)
INSERT INTO TCS_EMPLOYEES VALUES (9,'COAMBATORE','SIDDARTH','MANAGER',2500)
INSERT INTO TCS_EMPLOYEES VALUES (10,'MYSORE','KIRAN','MODULE LEAD',3000)

/* 1ST USECASE */

SELECT EMP_POSITION,COUNT(*) AS TOTAL FROM TCS_EMPLOYEES GROUP BY EMP_POSITION

SELECT EMP_POSITION,COUNT(*) AS TOTAL,SUM(EMPSALARY) AS TOTAL_SAL FROM TCS_EMPLOYEES GROUP BY EMP_POSITION

SELECT EMP_POSITION,COUNT(*) AS TOTAL,SUM(EMPSALARY) AS TOTAL_SAL,MAX(EMPSALARY) AS MAX_VALUE FROM TCS_EMPLOYEES GROUP BY EMP_POSITION

SELECT EMP_POSITION,COUNT(*) AS TOTAL,SUM(EMPSALARY) AS TOTAL_SAL FROM TCS_EMPLOYEES GROUP BY EMP_POSITION
/* 2ND USECASE */

SELECT EMP_POSITION,COUNT(*) AS TOTAL,SUM(EMPSALARY) AS TOTAL_SAL FROM TCS_EMPLOYEES GROUP BY EMP_POSITION HAVING SUM(EMPSALARY) > 6000