/* CREATE OWN DATABASE */
CREATE DATABASE AMAZON

/* ACTIVATE DATABASE */
USE AMAZON

/* DDL OPERATIONS */
CREATE TABLE EMPLOYEE_DETAILS (EMP_ID INT,EMPNAME CHAR(10),EMPAGE TINYINT,EMPSALARY MONEY)

/* WANT TO SHOW THE TABLE */
SELECT * FROM EMPLOYEE_DETAILS

/* ALTER */
ALTER TABLE EMPLOYEE_DETAILS ALTER COLUMN  EMPAGE INT  /* This command changes the data type of a column */

ALTER TABLE EMPLOYEE_DETAILS ADD EMPLOC CHAR(10)	/* This command adds a new column to the data base*/ 

ALTER TABLE EMPLOYEE_DETAILS DROP COLUMN EMPSALARY	/* This command deletes the entire column of a table */

ALTER TABLE EMPLOYEE_DETAILS RENAME COLUMN EMPAGE to EMP_AGE	/* This command don't work because we don't have RENAME key word for that we have SP_RENAME*/

/* SP_RENAME -> CHANGE THE COLUMN NAME */
SP_RENAME 'EMPLOYEE_DETAILS.EMPLOC','EMPAREA'	/* Used to rename a column in the table */

SP_RENAME 'EMPLOYEE_DETAILS','EMP_DATA'		/* Used to change the name of the table */
SP_RENAME 'EMP_DATA','EMPLOYEE_DETAILS'

/* DML OPERATIONS */
INSERT INTO EMPLOYEE_DETAILS VALUES (1,'JOHN',27,1200)
INSERT INTO EMPLOYEE_DETAILS VALUES (2,'PETER',37,180)
INSERT INTO EMPLOYEE_DETAILS VALUES (3,'MICHEAL',17,100)
INSERT INTO EMPLOYEE_DETAILS VALUES (4,'BRAD',41,1800)
INSERT INTO EMPLOYEE_DETAILS VALUES (5,'HENRY',23,1300) 

INSERT INTO EMPLOYEE_DETAILS (EMP_ID,EMPNAME,EMPSALARY) VALUES (6,'BALA',4000) /* used to insert specified data into table */

INSERT INTO EMPLOYEE_DETAILS VALUES (7,'JOHNI',27,NULL),(8,'PETEER',30,NULL)

/* UPDATE */
UPDATE EMPLOYEE_DETAILS SET EMPAREA=800 WHERE EMPNAME='BRAD'
UPDATE EMPLOYEE_DETAILS SET EMPAGE=47 WHERE EMPNAME='MICHEAL'


/* DELETE */
DELETE EMPLOYEE_DETAILS
DELETE EMPLOYEE_DETAILS WHERE EMPNAME='BRAD'
/* TRUNCATE */
TRUNCATE TABLE EMPLOYEE_DETAILS 

/* DROP */

DROP TABLE EMPLOYEE_DETAILS

SELECT *FROM EMPLOYEE_DETAILS