
/* JOINS EXAMPLE-1*/

CREATE TABLE EMPLOYEE_2024 (EMPID INT,EMPNAME CHAR(10),EMPSALARY MONEY)
CREATE TABLE EMPLOYEE_2025 (EMPID INT,EMPNAME CHAR(10),EMPSALARY MONEY)

SELECT *FROM EMPLOYEE_2024
SELECT *FROM EMPLOYEE_2025

INSERT INTO EMPLOYEE_2024 VALUES (1,'JOHN',1200)
INSERT INTO EMPLOYEE_2024 VALUES (2,'PETER',1200)
INSERT INTO EMPLOYEE_2024 VALUES (3,'BRAD',1800)
INSERT INTO EMPLOYEE_2024 VALUES (4,'SMITH',2200)
INSERT INTO EMPLOYEE_2024 VALUES (5,'MICHEAL',2400)

/* ANSI JOINS -> ON CONDITION */

INNER_JOIN:
-----------

SELECT *FROM EMPLOYEE_2024 INNER JOIN EMPLOYEE_2025 ON EMPLOYEE_2024.EMPID = EMPLOYEE_2025.EMPID

OUTER_JOIN:
-----------
SELECT *FROM EMPLOYEE_2024 LEFT OUTER JOIN EMPLOYEE_2025 ON EMPLOYEE_2024.EMPID = EMPLOYEE_2025.EMPID

SELECT *FROM EMPLOYEE_2024 RIGHT OUTER JOIN EMPLOYEE_2025 ON EMPLOYEE_2024.EMPID = EMPLOYEE_2025.EMPID

SELECT *FROM EMPLOYEE_2024 FULL OUTER JOIN EMPLOYEE_2025 ON EMPLOYEE_2024.EMPID = EMPLOYEE_2025.EMPID

SELECT *FROM EMPLOYEE_2024

CROSS_JOIN:
-----------
SELECT * FROM EMPLOYEE_2024 CROSS JOIN EMPLOYEE_2025

EQUI_JOIN:
-----------

SELECT *FROM EMPLOYEE_2024,EMPLOYEE_2025 WHERE EMPLOYEE_2024.EMPID = EMPLOYEE_2025.EMPID

NON_EQUI_JOIN:
---------------

SELECT *FROM EMPLOYEE_2024,EMPLOYEE_2025 WHERE EMPLOYEE_2024.EMPID > EMPLOYEE_2025.EMPID

/*JOIN EXAMPLE-2 */

CREATE TABLE EMPLOYEE (ID TINYINT,EMPNAME VARCHAR(10),EMPSALARY MONEY)
CREATE TABLE STUDENT (ID TINYINT,STDNAME VARCHAR(20),STDMARKS INT)

/* INSERT DATA INTO EMPLOYEE LIKE CUI */
INSERT INTO EMPLOYEE VALUES (1,'SAI',2000)
INSERT INTO EMPLOYEE VALUES (2,'KUMAR',4000)
INSERT INTO EMPLOYEE VALUES (3,'KIRAN',6000)
INSERT INTO EMPLOYEE VALUES (4,'SHAIK',8000)
INSERT INTO EMPLOYEE VALUES (5,'KRISHNA',10000)
INSERT INTO EMPLOYEE VALUES (6,'GOUTHAM',1000)
INSERT INTO EMPLOYEE VALUES (7,'VERA',3000)

/* SHOW THE TABLE */
SELECT *FROM EMPLOYEE

SELECT *FROM STUDENT

/* INNER JOIN */

SELECT *FROM EMPLOYEE INNER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

/* LEFT OUTER JOIN */
SELECT *FROM EMPLOYEE LEFT OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

/* RIGHT OUTER JOIN */
SELECT *FROM EMPLOYEE RIGHT OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

/* FULL OUTER JOIN */
SELECT *FROM EMPLOYEE FULL OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

/* CROSS JOIN */
SELECT *FROM EMPLOYEE CROSS JOIN STUDENT

/* EQUI JOIN */
SELECT *FROM EMPLOYEE,STUDENT WHERE EMPLOYEE.ID=STUDENT.ID

/* NON-EQUI JOIN */
SELECT *FROM EMPLOYEE,STUDENT WHERE EMPLOYEE.ID > STUDENT.ID


/* JOINS EXAMPLE-3*/
CREATE TABLE EMPLOYEE (ID INT,EMPNAME CHAR(10),EMPSALARY MONEY)

INSERT INTO EMPLOYEE VALUES (1,'KIRAN',100)
INSERT INTO EMPLOYEE VALUES (2,'KUMAR',150)
INSERT INTO EMPLOYEE VALUES (3,'SAI',180)
INSERT INTO EMPLOYEE VALUES (4,'PRAVEEN',200)
INSERT INTO EMPLOYEE VALUES (5,'GOUTHAM',250)
INSERT INTO EMPLOYEE VALUES (6,'ANAND',350)
INSERT INTO EMPLOYEE VALUES (7,'ARAVIND',400)

SELECT *FROM EMPLOYEE



CREATE TABLE STUDENT (ID INT,STDNAME CHAR(10),STDLOC CHAR(10))

INSERT INTO STUDENT VALUES (11,'JOHN','UK')
INSERT INTO STUDENT VALUES (12,'PETER','UK')
INSERT INTO STUDENT VALUES (1,'HARRY','USA')
INSERT INTO STUDENT VALUES (13,'SMITH','INDIA')
INSERT INTO STUDENT VALUES (2,'MICHEAL','JAPAN')
INSERT INTO STUDENT VALUES (14,'SURYA','CHINA')
INSERT INTO STUDENT VALUES (3,'KARTHIK','RUSSIA')


SELECT *FROM STUDENT
SELECT *FROM EMPLOYEE

ANSI_JOINS:

INNER_JOIN:
SELECT *FROM EMPLOYEE INNER JOIN STUDENT ON EMPLOYEE.ID = STUDENT.ID

LEFT_OUTER_JOIN:
SELECT *FROM EMPLOYEE LEFT OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

RIGHT_OUTER_JOIN:
SELECT *FROM EMPLOYEE RIGHT OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

FULL_OUTER_JOIN:
SELECT *FROM EMPLOYEE FULL OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID


CROSS_JOIN:
SELECT *FROM STUDENT CROSS JOIN EMPLOYEE

NON_ANSI_JOINS:

EQUI_JOIN:

SELECT *FROM EMPLOYEE,STUDENT WHERE EMPLOYEE.ID = STUDENT.ID

NON_EQUI_JOIN:

SELECT *FROM EMPLOYEE,STUDENT WHERE STUDENT.ID > EMPLOYEE.ID
