/* SET OPERATORS */

CREATE TABLE NETFLIX (NET_MOV_ID INT,NET_MOV_NAME CHAR(20),NET_MOV_BUG MONEY)
CREATE TABLE PRIME (PRI_MOV_ID INT,PRI_MOV_NAME CHAR(20),PRI_MOV_BUG MONEY)

INSERT INTO NETFLIX VALUES (1,'PB',100)
INSERT INTO NETFLIX VALUES (2,'VIKING',200)
INSERT INTO NETFLIX VALUES (3,'GOT',300)
INSERT INTO NETFLIX VALUES (4,'MONEYHEIST',400)
INSERT INTO NETFLIX VALUES (5,'SKYWALK',500)

INSERT INTO PRIME VALUES (10,'SSRED',1000)
INSERT INTO PRIME VALUES (11,'ANACONDA',2000)
INSERT INTO PRIME VALUES (2,'VIKING',200)
INSERT INTO PRIME VALUES (13,'SNAKES',3000)
INSERT INTO PRIME VALUES (14,'CONJURING',4000)
INSERT INTO PRIME VALUES (4,'MONEYHEIST',400)




SELECT *FROM NETFLIX
SELECT *FROM PRIME

UNION:

SELECT *FROM NETFLIX
UNION
SELECT *FROM PRIME

UNIONALL:

SELECT *FROM NETFLIX
UNION ALL
SELECT *FROM PRIME

INTERSECTION:

SELECT *FROM NETFLIX
INTERSECT
SELECT *FROM PRIME

EXCEPT:
SELECT *FROM NETFLIX EXCEPT SELECT *FROM PRIME 
