USE AMAZON

/* TINYINT is used when we have large data and small values to them*/
CREATE TABLE EMPLOYEE_DETAILS (EMPID INT,EMPNAME CHAR(10),EMPAGE TINYINT)

SELECT *FROM EMPLOYEE_DETAILS

/* NULL point*/
INSERT INTO EMPLOYEE_DETAILS VALUES (1,'JOHN',27),(2,'PETER',30)
INSERT INTO EMPLOYEE_DETAILS VALUES (3,'SMITH',NULL)

INSERT INTO EMPLOYEE_DETAILS VALUES (NULL,NULL,NULL)

UPDATE EMPLOYEE_DETAILS SET EMPAGE=50 WHERE EMPID=3

UPDATE EMPLOYEE_DETAILS SET EMPAGE=60 WHERE EMPAGE IS NULL

/* IDENTITY SEED INCREMENT */

/* INDENTITY */

CREATE TABLE MOVIES (MOVIE_ID INT IDENTITY,MOVIE_NAME VARCHAR(20),MOVIE_REV INT)
SELECT *FROM MOVIES

INSERT INTO MOVIES VALUES ('AVENGERS',100)
INSERT INTO MOVIES VALUES ('AVATAR',200)

DROP TABLE MOVIES

/* DEFAULT CONCEPT */

SET IDENTITY_INSERT MOVIES OFF
INSERT INTO MOVIES VALUES ('AVENGERS',100)
INSERT INTO MOVIES VALUES ('AVATAR',200)
INSERT INTO MOVIES VALUES ('FANDF',300)
INSERT INTO MOVIES VALUES ('MISSION IMPOSSIBLE',400)

/* INSERT DATA EXPLICITLY */
SET IDENTITY_INSERT MOVIES ON
INSERT INTO MOVIES (MOVIE_ID,MOVIE_NAME,MOVIE_REV) VALUES (21,'AVENGERS',100)
INSERT INTO MOVIES (MOVIE_ID,MOVIE_NAME,MOVIE_REV) VALUES (22,'AVATAR',200)
INSERT INTO MOVIES (MOVIE_ID,MOVIE_NAME,MOVIE_REV) VALUES (23,'FANDF',300)
INSERT INTO MOVIES (MOVIE_ID,MOVIE_NAME,MOVIE_REV) VALUES (24,'MISSION IMPOSSIBLE',400)

/* MANUAL INSERT*/
CREATE TABLE STUDENT_DETAILS (STDID INT IDENTITY(21,1),STDNAME VARCHAR(10),STDCOURSE CHAR(10))

SELECT *FROM STUDENT_DETAILS

INSERT INTO STUDENT_DETAILS VALUES ('PREM','AWS')
INSERT INTO STUDENT_DETAILS VALUES ('KIRAN','DA')

DROP TABLE STUDENT_DETAILS

CREATE TABLE EMPLOYEE (EMPID INT IDENTITY(100,5),EMPNAME CHAR(20),EMPSALARY MONEY,EMPLOC CHAR(10))

SELECT *FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES ('JOHN',1200,'HYD')
INSERT INTO EMPLOYEE VALUES ('PETER',1300,'CHENNAI')
INSERT INTO EMPLOYEE VALUES ('HARRY',1400,'PUNE')
INSERT INTO EMPLOYEE VALUES ('SMITH',1800,'BNG')
INSERT INTO EMPLOYEE VALUES ('MICHEAL',1900,'DELHI')


/* IDENTITY */

CREATE TABLE EMPLOYEE (EMPID INT IDENTITY(100,5),EMPNAME CHAR(10),EMPSALARY MONEY)

INSERT INTO EMPLOYEE VALUES ('KAMAL',100)
INSERT INTO EMPLOYEE VALUES ('KUMAR',150)
INSERT INTO EMPLOYEE VALUES ('SAI',200)
INSERT INTO EMPLOYEE VALUES ('SHIVA',250)
INSERT INTO EMPLOYEE VALUES ('PRASAD',300)
INSERT INTO EMPLOYEE VALUES ('KKKKK',800)


SET IDENTITY_INSERT EMPLOYEE OFF
INSERT INTO EMPLOYEE (EMPID,EMPNAME,EMPSALARY) VALUES (6,'ASHOK',400)

SET IDENTITY_INSERT EMPLOYEE ON
INSERT INTO EMPLOYEE (EMPID,EMPNAME,EMPSALARY) VALUES (7,'ASHWAK',500)

SELECT *FROM EMPLOYEE

DELETE FROM EMPLOYEE
