/* primary key and forgein key */

USE NETFLIX

CREATE TABLE EMP_PROFESSIONAL_DETAILS (EMPID INT PRIMARY KEY,EMPNAME CHAR(10),EMPSALARY MONEY)
CREATE TABLE EMP_PERSONAL_DETAILS (CITY CHAR(10),COMPANY VARCHAR(10),EXPERIENCE TINYINT,EMPID INT FOREIGN KEY REFERENCES EMP_PROFESSIONAL_DETAILS(EMPID) ON UPDATE CASCADE ON DELETE CASCADE)

SELECT *FROM EMP_PROFESSIONAL_DETAILS
SELECT *FROM EMP_PERSONAL_DETAILS

RULES:

INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (1,'JOHN',1200)
INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (2,'PETER',1400)
INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (3,'STEVE',1800)
INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (4,'BRAD',2200)
INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (5,'SMITH',1900)

INSERT INTO EMP_PERSONAL_DETAILS VALUES ('HYD','GOOGLE',1,1)
INSERT INTO EMP_PERSONAL_DETAILS VALUES ('PUNE','IBM',11,2)
INSERT INTO EMP_PERSONAL_DETAILS VALUES ('NOIDA','NVIDIA',12,3)
INSERT INTO EMP_PERSONAL_DETAILS VALUES ('BANG','INFOSYS',5,4)
INSERT INTO EMP_PERSONAL_DETAILS VALUES ('CHEN','MSFT',2,5)

INSERT INTO EMP_PERSONAL_DETAILS VALUES ('NOIDA','WIPRO',9,6)


UPDATE:

UPDATE EMP_PROFESSIONAL_DETAILS SET EMPNAME='KUMAR' WHERE EMPID=1

UPDATE EMP_PROFESSIONAL_DETAILS SET EMPSALARY=3000 WHERE EMPID=3

UPDATE EMP_PROFESSIONAL_DETAILS SET EMPID=30 WHERE EMPID=3

UPDATE EMP_PERSONAL_DETAILS SET EXPERIENCE=10 WHERE EMPID=2

UPDATE EMP_PERSONAL_DETAILS SET EMPID=20 WHERE EMPID=2


DELETE EMP_PROFESSIONAL_DETAILS WHERE EMPID=4

DELETE EMP_PERSONAL_DETAILS WHERE EMPID=4

DROP TABLE EMP_PROFESSIONAL_DETAILS
DROP TABLE EMP_PERSONAL_DETAILS

SELECT *FROM EMP_PROFESSIONAL_DETAILS
SELECT *FROM EMP_PERSONAL_DETAILS 

INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (6,'LAILA',NULL)
INSERT INTO EMP_PROFESSIONAL_DETAILS VALUES (NULL,'LAILA',5000)


INSERT INTO EMP_PERSONAL_DETAILS VALUES ('HYD','GOOGLE',1,1)

INSERT INTO EMP_PERSONAL_DETAILS VALUES ('WARANGAL','TIT',3,2)

UPDATE EMP_PROFESSIONAL_DETAILS SET EMPID=20 WHERE EMPID=2

DELETE EMP_PROFESSIONAL_DETAILS WHERE EMPID=20